// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// Webpage is an object representing the database table.
type Webpage struct {
	URL           string     `boil:"url" json:"url" toml:"url" yaml:"url"`
	Title         string     `boil:"title" json:"title" toml:"title" yaml:"title"`
	Description   string     `boil:"description" json:"description" toml:"description" yaml:"description"`
	Content       string     `boil:"content" json:"content" toml:"content" yaml:"content"`
	Links         types.JSON `boil:"links" json:"links" toml:"links" yaml:"links"`
	RetrievalTime time.Time  `boil:"retrieval_time" json:"retrieval_time" toml:"retrieval_time" yaml:"retrieval_time"`

	R *webpageR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L webpageL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var WebpageColumns = struct {
	URL           string
	Title         string
	Description   string
	Content       string
	Links         string
	RetrievalTime string
}{
	URL:           "url",
	Title:         "title",
	Description:   "description",
	Content:       "content",
	Links:         "links",
	RetrievalTime: "retrieval_time",
}

var WebpageTableColumns = struct {
	URL           string
	Title         string
	Description   string
	Content       string
	Links         string
	RetrievalTime string
}{
	URL:           "webpage.url",
	Title:         "webpage.title",
	Description:   "webpage.description",
	Content:       "webpage.content",
	Links:         "webpage.links",
	RetrievalTime: "webpage.retrieval_time",
}

// Generated where

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) LIKE(x string) qm.QueryMod    { return qm.Where(w.field+" LIKE ?", x) }
func (w whereHelperstring) NLIKE(x string) qm.QueryMod   { return qm.Where(w.field+" NOT LIKE ?", x) }
func (w whereHelperstring) ILIKE(x string) qm.QueryMod   { return qm.Where(w.field+" ILIKE ?", x) }
func (w whereHelperstring) NILIKE(x string) qm.QueryMod  { return qm.Where(w.field+" NOT ILIKE ?", x) }
func (w whereHelperstring) SIMILAR(x string) qm.QueryMod { return qm.Where(w.field+" SIMILAR TO ?", x) }
func (w whereHelperstring) NSIMILAR(x string) qm.QueryMod {
	return qm.Where(w.field+" NOT SIMILAR TO ?", x)
}
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpertypes_JSON struct{ field string }

func (w whereHelpertypes_JSON) EQ(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertypes_JSON) NEQ(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertypes_JSON) LT(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertypes_JSON) LTE(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertypes_JSON) GT(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertypes_JSON) GTE(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

type whereHelpertime_Time struct{ field string }

func (w whereHelpertime_Time) EQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertime_Time) NEQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertime_Time) LT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertime_Time) LTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertime_Time) GT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertime_Time) GTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var WebpageWhere = struct {
	URL           whereHelperstring
	Title         whereHelperstring
	Description   whereHelperstring
	Content       whereHelperstring
	Links         whereHelpertypes_JSON
	RetrievalTime whereHelpertime_Time
}{
	URL:           whereHelperstring{field: "\"webpage\".\"url\""},
	Title:         whereHelperstring{field: "\"webpage\".\"title\""},
	Description:   whereHelperstring{field: "\"webpage\".\"description\""},
	Content:       whereHelperstring{field: "\"webpage\".\"content\""},
	Links:         whereHelpertypes_JSON{field: "\"webpage\".\"links\""},
	RetrievalTime: whereHelpertime_Time{field: "\"webpage\".\"retrieval_time\""},
}

// WebpageRels is where relationship names are stored.
var WebpageRels = struct {
}{}

// webpageR is where relationships are stored.
type webpageR struct {
}

// NewStruct creates a new relationship struct
func (*webpageR) NewStruct() *webpageR {
	return &webpageR{}
}

// webpageL is where Load methods for each relationship are stored.
type webpageL struct{}

var (
	webpageAllColumns            = []string{"url", "title", "description", "content", "links", "retrieval_time"}
	webpageColumnsWithoutDefault = []string{"url"}
	webpageColumnsWithDefault    = []string{"title", "description", "content", "links", "retrieval_time"}
	webpagePrimaryKeyColumns     = []string{"url"}
	webpageGeneratedColumns      = []string{}
)

type (
	// WebpageSlice is an alias for a slice of pointers to Webpage.
	// This should almost always be used instead of []Webpage.
	WebpageSlice []*Webpage
	// WebpageHook is the signature for custom Webpage hook methods
	WebpageHook func(context.Context, boil.ContextExecutor, *Webpage) error

	webpageQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	webpageType                 = reflect.TypeOf(&Webpage{})
	webpageMapping              = queries.MakeStructMapping(webpageType)
	webpagePrimaryKeyMapping, _ = queries.BindMapping(webpageType, webpageMapping, webpagePrimaryKeyColumns)
	webpageInsertCacheMut       sync.RWMutex
	webpageInsertCache          = make(map[string]insertCache)
	webpageUpdateCacheMut       sync.RWMutex
	webpageUpdateCache          = make(map[string]updateCache)
	webpageUpsertCacheMut       sync.RWMutex
	webpageUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var webpageAfterSelectMu sync.Mutex
var webpageAfterSelectHooks []WebpageHook

var webpageBeforeInsertMu sync.Mutex
var webpageBeforeInsertHooks []WebpageHook
var webpageAfterInsertMu sync.Mutex
var webpageAfterInsertHooks []WebpageHook

var webpageBeforeUpdateMu sync.Mutex
var webpageBeforeUpdateHooks []WebpageHook
var webpageAfterUpdateMu sync.Mutex
var webpageAfterUpdateHooks []WebpageHook

var webpageBeforeDeleteMu sync.Mutex
var webpageBeforeDeleteHooks []WebpageHook
var webpageAfterDeleteMu sync.Mutex
var webpageAfterDeleteHooks []WebpageHook

var webpageBeforeUpsertMu sync.Mutex
var webpageBeforeUpsertHooks []WebpageHook
var webpageAfterUpsertMu sync.Mutex
var webpageAfterUpsertHooks []WebpageHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Webpage) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range webpageAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Webpage) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range webpageBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Webpage) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range webpageAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Webpage) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range webpageBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Webpage) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range webpageAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Webpage) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range webpageBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Webpage) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range webpageAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Webpage) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range webpageBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Webpage) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range webpageAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddWebpageHook registers your hook function for all future operations.
func AddWebpageHook(hookPoint boil.HookPoint, webpageHook WebpageHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		webpageAfterSelectMu.Lock()
		webpageAfterSelectHooks = append(webpageAfterSelectHooks, webpageHook)
		webpageAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		webpageBeforeInsertMu.Lock()
		webpageBeforeInsertHooks = append(webpageBeforeInsertHooks, webpageHook)
		webpageBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		webpageAfterInsertMu.Lock()
		webpageAfterInsertHooks = append(webpageAfterInsertHooks, webpageHook)
		webpageAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		webpageBeforeUpdateMu.Lock()
		webpageBeforeUpdateHooks = append(webpageBeforeUpdateHooks, webpageHook)
		webpageBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		webpageAfterUpdateMu.Lock()
		webpageAfterUpdateHooks = append(webpageAfterUpdateHooks, webpageHook)
		webpageAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		webpageBeforeDeleteMu.Lock()
		webpageBeforeDeleteHooks = append(webpageBeforeDeleteHooks, webpageHook)
		webpageBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		webpageAfterDeleteMu.Lock()
		webpageAfterDeleteHooks = append(webpageAfterDeleteHooks, webpageHook)
		webpageAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		webpageBeforeUpsertMu.Lock()
		webpageBeforeUpsertHooks = append(webpageBeforeUpsertHooks, webpageHook)
		webpageBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		webpageAfterUpsertMu.Lock()
		webpageAfterUpsertHooks = append(webpageAfterUpsertHooks, webpageHook)
		webpageAfterUpsertMu.Unlock()
	}
}

// OneG returns a single webpage record from the query using the global executor.
func (q webpageQuery) OneG(ctx context.Context) (*Webpage, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single webpage record from the query.
func (q webpageQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Webpage, error) {
	o := &Webpage{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for webpage")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all Webpage records from the query using the global executor.
func (q webpageQuery) AllG(ctx context.Context) (WebpageSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all Webpage records from the query.
func (q webpageQuery) All(ctx context.Context, exec boil.ContextExecutor) (WebpageSlice, error) {
	var o []*Webpage

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Webpage slice")
	}

	if len(webpageAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all Webpage records in the query using the global executor
func (q webpageQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all Webpage records in the query.
func (q webpageQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count webpage rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q webpageQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q webpageQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if webpage exists")
	}

	return count > 0, nil
}

// Webpages retrieves all the records using an executor.
func Webpages(mods ...qm.QueryMod) webpageQuery {
	mods = append(mods, qm.From("\"webpage\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"webpage\".*"})
	}

	return webpageQuery{q}
}

// FindWebpageG retrieves a single record by ID.
func FindWebpageG(ctx context.Context, uRL string, selectCols ...string) (*Webpage, error) {
	return FindWebpage(ctx, boil.GetContextDB(), uRL, selectCols...)
}

// FindWebpage retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindWebpage(ctx context.Context, exec boil.ContextExecutor, uRL string, selectCols ...string) (*Webpage, error) {
	webpageObj := &Webpage{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"webpage\" where \"url\"=$1", sel,
	)

	q := queries.Raw(query, uRL)

	err := q.Bind(ctx, exec, webpageObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from webpage")
	}

	if err = webpageObj.doAfterSelectHooks(ctx, exec); err != nil {
		return webpageObj, err
	}

	return webpageObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Webpage) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Webpage) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no webpage provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(webpageColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	webpageInsertCacheMut.RLock()
	cache, cached := webpageInsertCache[key]
	webpageInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			webpageAllColumns,
			webpageColumnsWithDefault,
			webpageColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(webpageType, webpageMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(webpageType, webpageMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"webpage\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"webpage\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into webpage")
	}

	if !cached {
		webpageInsertCacheMut.Lock()
		webpageInsertCache[key] = cache
		webpageInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single Webpage record using the global executor.
// See Update for more documentation.
func (o *Webpage) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the Webpage.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Webpage) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	webpageUpdateCacheMut.RLock()
	cache, cached := webpageUpdateCache[key]
	webpageUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			webpageAllColumns,
			webpagePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update webpage, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"webpage\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, webpagePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(webpageType, webpageMapping, append(wl, webpagePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update webpage row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for webpage")
	}

	if !cached {
		webpageUpdateCacheMut.Lock()
		webpageUpdateCache[key] = cache
		webpageUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q webpageQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q webpageQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for webpage")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for webpage")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o WebpageSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o WebpageSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), webpagePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"webpage\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, webpagePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in webpage slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all webpage")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Webpage) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Webpage) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no webpage provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(webpageColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	webpageUpsertCacheMut.RLock()
	cache, cached := webpageUpsertCache[key]
	webpageUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			webpageAllColumns,
			webpageColumnsWithDefault,
			webpageColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			webpageAllColumns,
			webpagePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert webpage, could not build update column list")
		}

		ret := strmangle.SetComplement(webpageAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(webpagePrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert webpage, could not build conflict column list")
			}

			conflict = make([]string, len(webpagePrimaryKeyColumns))
			copy(conflict, webpagePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"webpage\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(webpageType, webpageMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(webpageType, webpageMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert webpage")
	}

	if !cached {
		webpageUpsertCacheMut.Lock()
		webpageUpsertCache[key] = cache
		webpageUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single Webpage record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Webpage) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single Webpage record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Webpage) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Webpage provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), webpagePrimaryKeyMapping)
	sql := "DELETE FROM \"webpage\" WHERE \"url\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from webpage")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for webpage")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q webpageQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q webpageQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no webpageQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from webpage")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for webpage")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o WebpageSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o WebpageSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(webpageBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), webpagePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"webpage\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, webpagePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from webpage slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for webpage")
	}

	if len(webpageAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Webpage) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no Webpage provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Webpage) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindWebpage(ctx, exec, o.URL)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *WebpageSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty WebpageSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *WebpageSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := WebpageSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), webpagePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"webpage\".* FROM \"webpage\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, webpagePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in WebpageSlice")
	}

	*o = slice

	return nil
}

// WebpageExistsG checks if the Webpage row exists.
func WebpageExistsG(ctx context.Context, uRL string) (bool, error) {
	return WebpageExists(ctx, boil.GetContextDB(), uRL)
}

// WebpageExists checks if the Webpage row exists.
func WebpageExists(ctx context.Context, exec boil.ContextExecutor, uRL string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"webpage\" where \"url\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, uRL)
	}
	row := exec.QueryRowContext(ctx, sql, uRL)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if webpage exists")
	}

	return exists, nil
}

// Exists checks if the Webpage row exists.
func (o *Webpage) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return WebpageExists(ctx, exec, o.URL)
}
