CREATE EXTENSION IF NOT EXISTS "age";
CREATE EXTENSION IF NOT EXISTS "postgis";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "vector";

-- this user is used internally for monitoring (pgweb for example)
DO
$do$
BEGIN
   IF NOT EXISTS (
      SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'root'
   ) THEN
      CREATE ROLE root WITH SUPERUSER LOGIN INHERIT CREATEDB CREATEROLE REPLICATION PASSWORD '1UdEQQTMBGCCWxvY2FsaG9zdIcEfwAAATAdBgNVHQ4EFgQUgGAHp2OojO06lrYu';
   END IF;
END
$do$;
